INSERT INTO currencies (name)
VALUES ('EUR'),
       ('USD'),
       ('GBP');

INSERT INTO users (name)
VALUES ('John Doe'),
       ('John Smith'),
       ('Victorina Skyles'),
       ('Virgen Grace'),
       ('Sherron Milliman'),
       ('Farrah Holben'),
       ('Claudette Eleby'),
       ('Mari Abbas'),
       ('Winifred Laning'),
       ('Irma Griffy'),
       ('Danille Ector'),
       ('Maxine Peltz'),
       ('Julianna Schroth'),
       ('Lashawna Midgette'),
       ('Felicidad Lucian'),
       ('Bula Beil'),
       ('Maragaret Saucier'),
       ('Lera Zawislak'),
       ('Tessa Lefler'),
       ('Donnell Ary'),
       ('Debi Rote'),
       ('Kyle Partington'),
       ('Wan Weiler'),
       ('Lauren Drakeford'),
       ('Latrice Dayton'),
       ('Remona Corrigan'),
       ('Viva Leard'),
       ('Dollie Montesino'),
       ('Ernestina Flohr'),
       ('Almeda Eyre'),
       ('Junie Kluesner'),
       ('Jeri Hendricks'),
       ('Bethel Pesqueira'),
       ('Pete Blank'),
       ('Elias Juckett'),
       ('Jenell Beason'),
       ('Lavette Carabajal'),
       ('Adriana Buentello'),
       ('Adell Lapinski'),
       ('Isiah Ellman'),
       ('Evita Fortes'),
       ('Otis Neyman'),
       ('Beckie Sylvester'),
       ('Harley Kaczor'),
       ('Leisha Buzbee'),
       ('Alexander Heart'),
       ('Omer Throop'),
       ('Cyril Seeman'),
       ('Deandra Brignac'),
       ('Johnson Esser'),
       ('Donovan Hendrix'),
       ('Marine Letchworth');